export const AAD_ENUM = {
  GENAI_ACCESSTOKEN: 'GENAI-ACCESS-TOKEN',

  GENAI_IDTOKEN: 'GENAI-ID-TOKEN',

  GENAI_REFRESHTOKEN: 'GENAI-REFRESH-TOKEN',

  GENAI_EXPIRESON: 'GENAI-EXPIRESON',

  GENAI_ACCOUNT: 'GENAI-ACCOUNT',

  GENAI_TOKEN_TYPE: 'GENAI-TOKEN-TYPE',

  GENAI_ROLE: 'GENAI_ROLE',

  GENAI_EXPIRES_TIME: 'GENAI_EXPIRES_TIME',

  GENAI_REFRESH_EXPIRES_TIME: 'GENAI_REFRESH_EXPIRES_TIME',
};
